### ISSUE TITLE
[Bug] Problems with Adobe license

### ISSUE THREAD

**Issue by BrechtCorbeel** [LilyStilson/AErender-Launcher#13]
**What happened?**
Describe what exactly happened.

![Capture](https://user-images.githubusercontent.com/68238477/140617247-720e317f-be5e-4e74-9ae0-e0a7bba7424c.JPG)
![Capture 2](https://user-images.githubusercontent.com/68238477/140617249-5e792350-f30b-4217-b32a-42fb34b6a054.JPG)

**Comment by LilyStilson** [comment]
Umm, excuse me, but how is it in any way related to **Launcher**?

This is a problem with your Adobe account and that Adobe don't want to have you signed in more than 2 machines to use After Effects. It just says there: **"After Effects can only be activated on 2 devices simultaneously"**.

Sign out from one of them, that will make AE run on your current machine.

Of course there will be an error, After Effects couldn't start because of your license issue. This is not a **Launcher** problem.

**Comment by BrechtCorbeel** [comment]
> Umm, excuse me, but how is it in any way related to **Launcher**?
> 
> This is a problem with your Adobe account and that Adobe don't want to have you signed in more than 2 machines to use After Effects. It just says there: **"After Effects can only be activated on 2 devices simultaneously"**.
> 
> Sign out from one of them, that will make AE run on your current machine.
> 
> Of course there will be an error, After Effects couldn't start because of your license issue. This is not a **Launcher** problem.

Well that is the problem the launcher uses aerender.exe which is specifically needed to run ae render engine without a subscription and as a node so there should not be any activation launcher popping up in any way.

**Comment by LilyStilson** [comment]
> Well that is the problem the launcher uses aerender.exe which is specifically needed to run ae render engine without a subscription and as a node so there should not be any activation launcher popping up in any way.

Why shouldn't it pop out? aerender.exe is not a separate rendering engine. Adobe didn't just ripped of their rendering system and put it in a separate executable, no. Aerender will start After Effects with `-noui` flag, open project and start rendering with it. The log you see in a console is just a redirect from rendering log file.

You can't even use aerender.exe without AE being installed.
